[package]
name = "lab-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lab-engine = { version = "0.1.0", path = "../lab-engine" }
lab-midi = { version = "0.1.0", path = "../lab-midi" }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
