[package]
name = "lab-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
directories = "6.0.0"
lab-engine = { version = "0.1.0", path = "../lab-engine" }
lab-library = { version = "0.1.0", path = "../lab-library" }
lab-midi = { version = "0.1.0", path = "../lab-midi" }
rtrb = "0.4.0"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
