# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 Corey T. White

[package]
name = "labctl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Zoog debug and development CLI"

[dependencies]
lab-midi = { path = "../lab-midi" }
lab-engine = { path = "../lab-engine" }
rtrb = "0.4.0"
lab-core = { version = "0.1.0", path = "../lab-core" }
lab-library = { version = "0.1.0", path = "../lab-library" }
