# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 Corey T. White

[package]
name = "lab-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "CLAP plugin hosting, real-time audio output, and preset discovery"

[dependencies]
lab-midi = { path = "../lab-midi" }
clack-extensions = { git = "https://github.com/prokopyl/clack", rev = "27ca28391b57a61bad4bb5099288a7bf9247350d", version = "0.2.0", features = ["clack-host", "audio-ports", "note-ports", "log", "params", "preset-discovery", "timer"] }
clack-finder = { git = "https://github.com/prokopyl/clack", rev = "27ca28391b57a61bad4bb5099288a7bf9247350d", version = "0.1.0" }
clack-host = { git = "https://github.com/prokopyl/clack", rev = "27ca28391b57a61bad4bb5099288a7bf9247350d", version = "0.2.0" }
cpal = "0.18.2"
rtrb = "0.4.0"

[dev-dependencies]
clack-host = { git = "https://github.com/prokopyl/clack", rev = "27ca28391b57a61bad4bb5099288a7bf9247350d" }
